### ISSUE TITLE
FT5406 error

### ISSUE THREAD

**Issue by generalgruntin** [chundermike/rpi-fruitbox#11]
Hello!

I am working on making a custom jukebox and I'm having an issue setting up button controls. I got the software to run, put songs on it etc. however a few things occurred. First off I noticed that when I plug a USB keyboard into the pi, the pi recognizes the USB keyboard but the software does not. In other words the buttons on the USB keyboard do nothing when I press them using fruitbox. I am using the WallSmall skin.

Now I think this may be because the keyboard I'm using may not be compatible but I have no way of proving that to be the case,

I then tried to wire the buttons to the gpio pins. With the WallSmall skin, there are only 4 number buttons and I also added a left/right and play button. That was it.

I perused through the forum and found that retrogame could be used to map the gpio to keys. So I edited the pigrrl code accordingly to map the gpio to the specific keys I needed.

Still the buttons did nothing,

So from what I read I have to go to the button config to map the gpio pins to the keys/buttons,

But when I try to open the button-config it gives me an error saying "couldn't find device FT5406" which as I read on the forum is the 7 inch raspberry pi touchscreen. I'm not using a touch screen fir this. So I'm assuming that's the problem. Please let me know what I am doing wrong and how I can get the button controls working,

I'm using a raspberry pi 3 B and putty via ssh.

Let me know if you can help me.

**Comment by chundermike** [comment]
Please try version 1.14 and re- open the issue if it still doesn't work. 

Thanks
Mike
