### ISSUE TITLE
Keyboard not responding after setting autostart in console

### ISSUE THREAD

**Issue by Ferttoo** [chundermike/rpi-fruitbox#13]
Hi chundermike.
First, let me thank you for an exelent program. I have DW-jukebox running in the next room, an frankly, I would like to switch to Fruitbox.

Everything installed, works perfectly when starting in GUI and from console.
But when I created a .sh script, it starts perfectly. 
Suddenly the keyboard is offline. There is no way to fix this exept to sweep the pie and start over again. 

Im getting really good at installing your system now :)

Any Idea what im doing wrong?

Or...anyone else having the same strange behaviour? 

Regards Peter

***Update*** Finding hidden files, doin just like you have instructed in User guide, switching off gui finally worked fine. Im learning Linux one step at the time. Again, thanks for a great program!

**Comment by chundermike** [comment]
Glad it's working for you now. 
Mike
