### ISSUE TITLE
Feature Request: Mopidy Interfacing

### ISSUE THREAD

**Issue by VerboseModeTV** [chundermike/rpi-fruitbox#15]
Hi,

This is a GORGEOUS system you've created. Per your invitation, I have a feature request, though I'm not sure this is where you wanted it. But here goes:

During the summer I am a counselor at a camp called "Camp One Step" and I work with the teenagers. One of the biggest challenges during any downtime is how multiple campers turn into mini DJs with their bluetooth speakers and they all have Spotify and they ALL have different, non-overlapping tastes though the sound all tries to overlap.

Next year I'm going to be bringing a number of Maker projects and one of the ones I'm working on is a jukebox where campers can submit their favorite songs to a collaborative playlist and then add songs to a queue on a physical jukebox system with a single sound system instead of theirs.

I've been tinkering with Modipy and MPD. Mopidy gives me the backend I need (ability to read and play a collaborative playlist on Spotify) but I haven't yet found (or been able to develop) a good front-end.

So when I saw yours, I feel in love.

Would you consider adding the ability for Fruitbox to be able to interact with Spotify or Mopidy directly?

Thank for your time,

Chad

**Comment by chundermike** [comment]
Hi
Thanks for your interest.  This is something that I haven't much knowledge about but will have a think about how it could be integrated in the future.  If it's not too difficult I will certainly consider it. 

Thanks
Mike
