### ISSUE TITLE
Update source code?

### ISSUE THREAD

**Issue by 6alileo** [chundermike/rpi-fruitbox#19]
Hello - any chance you can update your git with the source code so we can build it for the latest? This is for the Odroid community which is running a fork of RetroPie called "RetroArena" specific for Odroid XU4

**Comment by chundermike** [comment]
Yes sorry...will update the source code over the weekend

**Comment by chundermike** [comment]
By the way, did you solve the sluggish behaviour (lack of GPU rendering)?

**Comment by 6alileo** [comment]
It's still sluggish in regards to input. Graphics wise, it's not too bad but could be smoother. I think once the input is resolved, it'll feel better. I'll have to see whats that like.

**Comment by 6alileo** [comment]
But I did figure out the way to configure inputs, that was my issue initially. But the new way seems better.

**Comment by chundermike** [comment]
Source code for v.1.4 is now updated
