### ISSUE TITLE
starts and go's back to the menu

### ISSUE THREAD

**Issue by jasclo** [chundermike/rpi-fruitbox#22]
i can not get this to work it starts and then go's back to the menu

**Comment by chundermike** [comment]
Hi
Can you be more specific? When it starts how far does it get? I.e. does it show the jukebox screen or just the spinning logo? Also what menu does it go back to?

Thanks
Mike

**Comment by jasclo** [comment]
Just the spinning logo

**Comment by chundermike** [comment]
Perhaps it can't find any songs... what error message did it print?

**Comment by jasclo** [comment]
Can't tell it goes so fast back to emulation station I am using arcade only
build

**Comment by chundermike** [comment]
Hi,
It's almost certainly not finding any songs.  You need to check that the MusicPath parameter in the skin config file is pointing to a directory where your MP3 files are stored.

**Comment by jasclo** [comment]
OK I will try again thanks
