### ISSUE TITLE
Error: Couldn't open configuration file 'granite' for input

### ISSUE THREAD

**Issue by GRVLK** [chundermike/rpi-fruitbox#28]
Hey @chundermike ,
Let me start by saying I love the idea and was totally wowed when I saw the videos of the software in action.  I've been trying to get mine up and running for a few weeks off and on, but I keep getting 'Error: Couldn't open configuration file 'x' for input'.  In this case x = granite, miketv, wurly.  Doesn't matter which skin I choose I get the same error.  I've tried re configuring the buttons and but no luck.  I'm using a Raspberry Pi 3B+ and a logitech K400 wireless keyboard,  I'm kind of a noob when it come to pi so I apologize if I'm missing something obvious.  At this point I'm about to reinstall raspbian and fruitbox and see if I have any more luck with that.  Any help would be appreciated

**Comment by chundermike** [comment]
Hi

Sorry to hear you're having trouble.  Could you tell me exactly what command you are entering to run fruitbox,  and which directory you are in. Also before running the fruitbox command,  can you type 'ls -al' (no quotes) from the same directory and see if it lists the skins directly. 

Cheers,
Mike

**Comment by GRVLK** [comment]
Hi Mike,
I’m using command ‘sudo ./fruitbox --cfg granite’ in the ‘~/rpi-fruitbox-master’ directory.  The list of rpi-fruitbox-master shows the skins directory, but not any skins directly.  When I run the command I get the spinning logo but immediately after I get kicked out with the error.
Thanks for the help.

**Comment by chundermike** [comment]
Hi

The cfg option needs to point to the skins configuration file, so you need to use the command 'sudo ./fruitbox --cfg skins/Granite/fruitbox.cfg'

Cheers 
Mike

**Comment by GRVLK** [comment]
That did it!  Thanks for the help!

**Comment by cavani76** [comment]
Ciao GRVLK ho il tuo stesso problema come hai risolto?

**Comment by chundermike** [comment]
Try granite.cfg :)
________________________________

**Comment by cavani76** [comment]
Ok Mike ti farò sapere intanto grazie mille

**Comment by cavani76** [comment]
Buongiorno Mike ho provato la skin granite ma purtroppo non va'. Altri consigli? Oppure devo reinstallare di nuovo fruitbox?

**Comment by chundermike** [comment]
Hi

Please send me the fruitbox.log file and I will check

Thanks
Mike
________________________________

**Comment by cavani76** [comment]
Mike ho aperto il file fruitbox log ma e vuoto

**Comment by cavani76** [comment]
Devo scriverci qualche cosa forse?

**Comment by cavani76** [comment]
Ho appena aperto il file fruitbox log ma e vuoto forse devo scrivere qualcosa?

**Comment by chundermike** [comment]
Strange! It shouldn't be empty.  Can you tell me exactly what your are typing on the command line to run fruitbox?
________________________________

**Comment by cavani76** [comment]
![16003619890351567843382196126717](https://user-images.githubusercontent.com/71391367/93503174-ff3d6880-f917-11ea-8489-52bd22397d83.jpg)

**Comment by cavani76** [comment]
Dopo aver provato ad inserire la skin granite nel file fruitbox log  mi esce questo

**Comment by chundermike** [comment]
What did you type in to start fruitbox? I would expect something like...

./fruitbox --cfg skins/granite/fruitbox.cfg
________________________________

**Comment by cavani76** [comment]
Proprio questo ho digitato

**Comment by cavani76** [comment]
Digito prima CD rpi- fruitbox-master/. E poi  digito sudo ./ --cfg skins/granite/fruitbox.cfg

**Comment by cavani76** [comment]
Scusa  sudo ./ Fruitbox -- cfg skin/granite/ fruitbox.cfg

**Comment by cavani76** [comment]
![16003644166277896150218883847699](https://user-images.githubusercontent.com/71391367/93507222-a670ce80-f91d-11ea-8137-91e859cb48de.jpg)

**Comment by chundermike** [comment]
That says it is looking for the walljuke skin. Check you have a skins directory in the fruitbox directory
________________________________

**Comment by cavani76** [comment]
C'è sia la cartella skin che il file skin txt

**Comment by cavani76** [comment]
A limite provo a reinstallare fruitbox e poi ti aggiorno perché potrebbe esservi qualche errore nel download forse

**Comment by chundermike** [comment]
Check the skin file contains all the skins. If so, you are probably not running fruitbox from its home directory. Open a command terminal, then type...

cd ~/rpi-fruitbox-master
./fruitbox --cfg skins/granite/fruitbox.cfg

Or for the skin chooser,  type...

./fruitbox --choose-cfg skins.txt
________________________________

**Comment by chundermike** [comment]
I would recommend Raspian Lite, not Raspian desktop
________________________________

**Comment by chundermike** [comment]
Looks like a network problem. Check your internet and try again :)
________________________________

**Comment by cavani76** [comment]
Ok grazie mille

**Comment by cavani76** [comment]
Come sempre gentilissimo

**Comment by cavani76** [comment]
Buongiorno Mike sai dove posso scaricare una versione precedente di fruitbox?  Attualmente stavo usando la 1.6 ma purtroppo mi da problemi grazie

**Comment by chundermike** [comment]
All previous versions are available on GitHub...click on the fruitbox executable file and select history, which will navigate you to all releases.

Out of interest , what problems are you having with the latest release?
________________________________

**Comment by cavani76** [comment]
Sulla versione 1.6 ho mappato i pulsa nti ma non riesco a capire bene dove inserire gli MP3 e come modificare la Path music nella skin desiderata

**Comment by cavani76** [comment]
Forse e per questo che non parte fruitbox

**Comment by cavani76** [comment]
Il resto dei passaggi li ho fatti perfettamente

**Comment by chundermike** [comment]
That hasn't changed in version 1.6.

You can put your mp3 files anywhere, and point to them using the MusicPath parameter in the skin cfg file (or --music-path command line argument).

For example...in a command terminal type...

cd /home/pi
mkdir music

Then copy all your mp3 files and/or mp3 folders to /home/pi/music

Then in the skin cfg...

MusicPath = /home/pi/music

...in bocca al lupo!

________________________________

**Comment by cavani76** [comment]
Scusa Mike se ti disturbo ancora ma credo che avrei bisogno di un video tutorial completo magari così faccio tutti i passaggi corretti e riesco a completare! Tu non potresti inviarmelo così quando completo tutto  ti invio anche la foto del mio jukebox fatto a mano! Grazie mille per il tuo aiuto

**Comment by cavani76** [comment]
Con altri lavori nessun problema ma con questo non so non ci rieso

**Comment by cavani76** [comment]
Infatti realizzo anche mini cabinet arcade

**Comment by cavani76** [comment]
![Uploading 1600846671180507895824732554676.jpg…]()

**Comment by cavani76** [comment]
![Uploading 16008475228477414655026926610052.jpg…]()

**Comment by cavani76** [comment]
Ciao Mike sono riuscito a fare partire il programma ho caricato anche gli MP3 e funzionano tutte le skins ma ho un problema audio .sto usando delle casse con jack 3.5  inserite nella Raspberry ma niente audio sai come aiutarmi?

**Comment by cavani76** [comment]
Forse devo impostare qualche settaggio?

**Comment by chundermike** [comment]
Hi,

Yes, you need to modify the system settings. Try ...

sudo raspi-config

And then look for the audio settings. If it's not obvious,  try googling for the solution...it's quite a common problem.

Mike
________________________________

**Comment by cavani76** [comment]
Ciao Mike ho risolto anche il problema audio 👍 volevo chiederti quali MP3 sono ideali  per fare riconoscere l'artista ed il brano

**Comment by cavani76** [comment]
Usi qualche formato in particolare?

**Comment by cavani76** [comment]
Ultima domanda come faccio a salvare la playlist nel database ho notato che ogni volta che avvio fruitbox deve sempre caricare i brani prima

**Comment by cavani76** [comment]
Ciao Mike ho risolto il problema audio👍 volevo chiederti se usi qualche tipo di MP3 in particolare per fare riconoscere a fruitbox gli artisti ed i brani

**Comment by cavani76** [comment]
Infine come salvo la playlist nel database

**Comment by chundermike** [comment]
Hi

You can save the playlist using the --save-playlist command line argument, and load it back in later using the --load-playlist option. Please read the user guide.

Also, fruitbox will recognise both IDv1 and IDv2 mp3 tags for the song title and artist (and many other tags), so normal mp3 files will work fine, as long as they have the correct metadata in them. You can always add this data yourself to the mp3 files by using free software such as mp3tag (for Windows)

Cheers
Mike
________________________________

**Comment by cavani76** [comment]
👍 grazie mille

**Comment by cavani76** [comment]
Ciao Mike come ti avevo promesso ti mando la foto del jukebox da me
realizzato .grazie per il tuo aiuto col software.by Cavani 76

Il mar 29 set 2020, 13:24 chundermike <notifications@github.com> ha scritto:

**Comment by cavani76** [comment]
Prova la skin walljuke
Versione 6.1

Il lun 11 ott 2021, 20:24 Pegabri ***@***.***> ha scritto:

**Comment by Pegabri** [comment]
> Ciao Mike ho risolto il problema audio👍 volevo chiederti se usi qualche tipo di MP3 in particolare per fare riconoscere a fruitbox gli artisti ed i brani

**Comment by Pegabri** [comment]
Ciao Cavani76, sono riuscito a far partire con WallJuke… ho solo un problema e ti chiedo aiuto. Ho eseguito il comando autostart ed è tutto ok , solo che quando forzo l’uscita alle casse (3.5) … perde il comando di auto start. Se voglio l autostart la musica esce in hdmi na senza auto start esce dalle casse. Come posso fare? 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻
