### ISSUE TITLE
Skin Chooser

### ISSUE THREAD

**Issue by Houndquake** [chundermike/rpi-fruitbox#38]
Is there a way to turn the skin chooser off?  I have everything set but I cant get it to just boot to the skin I want.

Thank you. Amazing Program by the way

Erik

**Comment by chundermike** [comment]
Yes, run fruitbox with the --cfg command line option and not the --choose-cfg option. See userguide.txt for details.

The fruitbox command is in the /etc/rc.local file, by the way.
