### ISSUE TITLE
Fruitbox

### ISSUE THREAD

**Issue by flynn14** [chundermike/rpi-fruitbox#39]
Can anyone help me i follow all the steps to install fruitbox on raspberry pi 3b but cant seem to get the skin config to work so i can map my usb music to my chosen skin aka Wurly

**Comment by chundermike** [comment]
If you use the SD image it will expect the music to be on a USB stick. If you want fruitbox to run the Wurly skin rather than the default skin chooser then you'll need to edit /etc/rc.local and change the fruitbox command (from --choose-cfg skins.txt to --cfg skins/Wurly/fruitbox.cfg)

**Comment by flynn14** [comment]
Thanks mike but if i copy my music onto my sd card music it works fine but i want to be able to leave my music on my usb drive so i can add more music later, but when i do that it come up with an error music path the path i am using is ./media/usb/Music and nothing sorry to be a pain

**Comment by chundermike** [comment]
If you read the userguide.txt there is a section near the end on how to set up the Pi to mount an SD drive automatically and set the music path correctly.

**Comment by flynn14** [comment]
Awesome thanks for that i am new to this that doc is an awesome help. Awesome job you have done great system
