### ISSUE TITLE
Joystick use

### ISSUE THREAD

**Issue by cybercloporte** [chundermike/rpi-fruitbox#4]
Hello, i can't make working joystick in fuitbox. In fruitbox.cfg, i have this : 
#[joystick]
#Bitmap = ../glass.png
#Offset = -10 -10
#Size 330 50
So i delete the #, but after reboot, fruitbox don't boot. There's no file named glass.png in the skin folder ! (walljuke skin).

**Comment by chundermike** [comment]
Solved on raspberry pi forum
