### ISSUE TITLE
X86/X64 version

### ISSUE THREAD

**Issue by DaVyper** [chundermike/rpi-fruitbox#43]
In the PI forums back in 2018 you indicated that you had a version you ran on Ubuntu while developing, Any chance on getting a copy of it, or the windows version you thought wouldn't be too much trouble??  I'd be happy with even one that ran under WSL, but i have a few Ubuntu boxes to play with it on too.  If i was more of a programmer i'd try compiling myself, but I'm more a graphics guy and would like on a PC for easier skin creation.

**Comment by chundermike** [comment]
Hi
If you follow the build instructions in build.txt you can build it for any linux distribution.  You'll have to remove the -D_RPI switch in the Makefile to remove any RPi specific code (I.e. GPIO support). You can also build for windows but you're more on your own for this, as I've never done it but it should be possible...Grab a copy of Microsoft visual community C/C++ dev suite and create a project with all the source code in. Then install the Allegro 5 libraries from the IDE. The libmpg123, there may already be precompiled libraries for windows available, if not you'll have to build your own using instructions from the libmpg123 community.
