### ISSUE TITLE
Configure issues

### ISSUE THREAD

**Issue by dennyknott** [chundermike/rpi-fruitbox#45]
![image](https://user-images.githubusercontent.com/71236162/93030881-6abfc700-f5f4-11ea-9a12-e5fb891cb1c7.jpeg)

I can't figure this out! It's driving me crazy!! I'm new at this.
I have been watching YouTube videos in different languages and still can't figure it out. There's nothing out there in English that tells you how to set it up from soup to nuts that I can fine￼.

Thanks for the help!

**Comment by chundermike** [comment]
The path is case sensitive...try Wurly, not wurly

**Comment by dennyknott** [comment]
Thanks Mike that was it!!
