### ISSUE TITLE
Error Starting...

### ISSUE THREAD

**Issue by Kazaster** [chundermike/rpi-fruitbox#5]
Total newbie here.  I Installed the folder using get, unzipped the archive, changed the permissions of the folder, and modified the .cfg file to change the Music folder location. When starting the program from command window 'sudo  ./fruitbox --cfg skins/WallJuke/fruitbox.cfg" ...I get an error...  ""./fruitbox: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory"".  No .db file is ever created in the rpi-fruitbox-master folder.  UPDATE - created totally new PI installation, set screen dimensions, pointed to music file folder. Up an running.  Problem was with dependencies maybe ? Library conflicts ?

**Comment by chundermike** [comment]
sounds like initial installation had a problem.  Glad it's working for you now.
