### ISSUE TITLE
Keyboard not loading...

### ISSUE THREAD

**Issue by Kazaster** [chundermike/rpi-fruitbox#6]
I have been able to start the program from the terminal or desktop executable script, but 50% of the time I get a 'keyboard not loading" error in the terminal and the program locks the terminal up.  I've tried deleting the .db file, some times it seems to work, but other time not. I've tried starting the program using crontab @reboot.  After a 20-second delay, the program runs an executable script that starts the program nearly all of the time, however...using crontab...I loose all input/control of the PI.  Fruitbox will run automatically, but accepts no keyboard inputs.  I have to SSH into the PI to reboot/exit crontab and/or the start.sh script.  Any Ideas ? Thanks !

**Comment by chundermike** [comment]
Please try running from the Pi booting straight to the console rather than from within the desktop GUI
