### ISSUE TITLE
Couldn‘t create fruitbox.db when using .ogv Files

### ISSUE THREAD

**Issue by SoerenRa** [chundermike/rpi-fruitbox#89]
Hey there, 

Great Work so far! I installed Fruitbox via the Image File provided. Unfortunately every Time I try to add .ogv Files to my Music Repository (for Music Videos) it says that it can’t create the DB. What am I missing?

**Comment by SoerenRa** [comment]
Update: With MikeTV the Video starts but it begins stuttering almost immediately. It gets worse and worse with time. Also there’s a Warning saying -> libpng warning: iCCP: known incorrect sRGB profile. What should I do?

**Comment by Witchboard** [comment]
I had that problem as well.  Determined that my files were just too big for it to handle.  Had to use ffmpeg to re-encode them to like 480 at 320k before they would playback without problems.
