### ISSUE TITLE
"Z" being replaced with "A" on song titles - Modern skin

### ISSUE THREAD

**Issue by rooktheklown** [chundermike/rpi-fruitbox#9]
I've noticed that when using the Modern skin, the letter "Z" is replaced with the letter "A" in the song titles. This results in titles such as "CRAAY TRAIN", "CRAAY FOR YOU",  and "CRAAY LITTLE THING CALLED LOVE". 

The issue is with the font itself, as the uppercase "Z" is a duplicate uppercase "A". The easiest fix seems to be changing the capitalize parameter to "false", since the lowercase letters are functionally identical to the uppercase, except that there is an actual "Z". 

I'll test this when I get home later to confirm.

**Comment by chundermike** [comment]
Thanks for spotting that...whatever fix you have, please let me know and I'll update the repo.

Cheers,
Mike

**Comment by rooktheklown** [comment]
I just tested, and changing the capitalize parameter to "false" fixed the issue, since the lowercase letters are identical to the uppercase (aside from Z, of course).

That said, it is pretty funny to have songs showing up as "CRAAY". I may put it back when I want to mess with people.

**Comment by PrdAmrican** [comment]
Wish I'd seen these posts before I pulled all my hair out, LOL.  I think I have fixed the font...
[TravellingFixed.zip](https://github.com/chundermike/rpi-fruitbox/files/2727695/TravellingFixed.zip)

BTW, love Fruitbox.

**Comment by chundermike** [comment]
Brilliant thanks.  Modern skin now updated (changed font reference in fruitbox.cfg) and uploaded TravellingFixed.ttf and deleted Travelling.ttf
